name: Deploy database to Azure

on:
  push:
    branches:
      - main
    paths:
      - "server/prisma/migrations/**"
  workflow_dispatch:

env:
  DATABASE_URL: ${{ secrets.AZURE_SQL_DATABASE_URL }}

jobs:
  migrate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: "18.x"

      - name: Install
        run: |
          cd server
          npm install

      - name: Deploy migration
        run: |
          cd server
          npm run migrate:deploy
